spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/log?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useSSL=false&tinyInt1isBit=false
    username: root
    password: admin
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 6000000
    socketTimeout: 0
    minIdle: 1
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 3000000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20






